/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
//he på daj
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author JR&Maggi
 */
public class Admin extends javax.swing.JFrame {

    private InfDB databas;
    private DefaultTableModel DMElev = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private DefaultTableModel DMLarare = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private DefaultTableModel DMKurser = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        connectDB();
        fyllTblElev();
        fyllTblLarare();
        fyllKursLärareComboBox();
        fyllÄmneComboBox();
        fyllTblKurser();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLoggaUtAdmin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jcbElevhem = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        lblPoäng = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fldAdd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        fldRemove = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKurser = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kursStartDatum = new com.toedter.calendar.JDateChooser();
        kursSlutDatum = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fldKursNamn = new javax.swing.JTextField();
        cbxÄmne = new javax.swing.JComboBox<>();
        cbxKursLärare = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblKursID = new javax.swing.JLabel();
        btnRegistreraKurs = new javax.swing.JButton();
        btnÄndraKurser = new javax.swing.JButton();
        btnTaBortKurser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblElevId = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegistreraElev = new javax.swing.JButton();
        btnÄndraElev = new javax.swing.JButton();
        btnTaBortElev = new javax.swing.JButton();
        txtfldElevNamn = new javax.swing.JTextField();
        txtfldElevEfternamn = new javax.swing.JTextField();
        txtfldSovsal = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblElev = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblLärarId = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtfldLärarNamn = new javax.swing.JTextField();
        txtfldLärarEfternamn = new javax.swing.JTextField();
        btnRegistreraLärare = new javax.swing.JButton();
        btnÄndraLärare = new javax.swing.JButton();
        btnTaBortLärare = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtfldLösenord = new javax.swing.JTextField();
        chkbx = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLarare = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Välkommen:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Förnamn");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Efternamn");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        btnLoggaUtAdmin.setText("Logga ut");
        btnLoggaUtAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoggaUtAdmin)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnLoggaUtAdmin)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Hem", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setText("Välj elevhem");

        jcbElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gryfindor", "Slytherin", "Hufflepuff", "Ravenclaw" }));
        jcbElevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbElevhemActionPerformed(evt);
            }
        });

        jLabel18.setText("Huspoäng:");

        jLabel20.setText("Lägga till huspoäng");

        btnAdd.setText("Lägg till");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel21.setText("Dra av huspoäng");

        btnRemove.setText("Dra av");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jcbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPoäng, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(fldRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(fldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAdd))))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoäng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(43, 43, 43)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Huspoäng", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Registrera, ändra och ta bort kurser");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKurser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKurser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKurserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKurser);

        jLabel2.setText("Kurslärare:");

        jLabel3.setText("Ämnestillhörighet:");

        kursStartDatum.getDateEditor().setEnabled(false);
        kursStartDatum.setDateFormatString("yyyy-MM-dd");

        kursSlutDatum.getDateEditor().setEnabled(false);
        kursSlutDatum.setDateFormatString("yyyy-MM-dd");

        jLabel19.setText("Kurs id:");

        jLabel23.setText("Kursnamn:");

        jLabel24.setText("Startdatum:");

        jLabel25.setText("Slutdatum:");

        btnRegistreraKurs.setText("Registreara");
        btnRegistreraKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraKursActionPerformed(evt);
            }
        });

        btnÄndraKurser.setText("Ändra");
        btnÄndraKurser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraKurserActionPerformed(evt);
            }
        });

        btnTaBortKurser.setText("Ta bort");
        btnTaBortKurser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortKurserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblKursID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldKursNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxKursLärare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kursSlutDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(kursStartDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnRegistreraKurs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnÄndraKurser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaBortKurser))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxÄmne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKursID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(fldKursNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxKursLärare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxÄmne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistreraKurs)
                            .addComponent(btnÄndraKurser)
                            .addComponent(btnTaBortKurser))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kurser", jPanel5);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Registrera, ändra och ta bort elever");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel8.setText("Elev ID:");

        jLabel10.setText("Förnamn:");

        jLabel11.setText("Efternamn:");

        jLabel12.setText("Sovsal:");

        btnRegistreraElev.setText("Registrera");
        btnRegistreraElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraElevActionPerformed(evt);
            }
        });

        btnÄndraElev.setText("Ändra");
        btnÄndraElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraElevActionPerformed(evt);
            }
        });

        btnTaBortElev.setText("Ta bort");
        btnTaBortElev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortElevActionPerformed(evt);
            }
        });

        txtfldElevNamn.setColumns(10);

        tblElev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblElev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblElevMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblElev);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRegistreraElev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnÄndraElev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaBortElev))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtfldSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfldElevNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(txtfldElevEfternamn))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblElevId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(lblElevId, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtfldElevNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtfldElevEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfldSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistreraElev)
                            .addComponent(btnÄndraElev)
                            .addComponent(btnTaBortElev))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Elever", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Registrera, ändra och ta bort Lärare");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Lärar ID:");

        jLabel15.setText("Förnamn:");

        jLabel16.setText("Efternamn:");

        btnRegistreraLärare.setText("Registrera");
        btnRegistreraLärare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraLärareActionPerformed(evt);
            }
        });

        btnÄndraLärare.setText("Ändra");
        btnÄndraLärare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraLärareActionPerformed(evt);
            }
        });

        btnTaBortLärare.setText("Ta Bort");
        btnTaBortLärare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortLärareActionPerformed(evt);
            }
        });

        jLabel14.setText("Lösenord:");

        chkbx.setText("Administratör");

        tblLarare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLarare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLarareMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLarare);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtfldLärarNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkbx)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfldLösenord, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfldLärarEfternamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblLärarId, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnRegistreraLärare)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnÄndraLärare)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(btnTaBortLärare))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(lblLärarId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtfldLärarNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtfldLärarEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtfldLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chkbx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistreraLärare)
                            .addComponent(btnÄndraLärare)
                            .addComponent(btnTaBortLärare))))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Lärare", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistreraElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraElevActionPerformed
        String fornamn = txtfldElevNamn.getText();
        String efternamn = txtfldElevEfternamn.getText();
        String sovsal = txtfldSovsal.getText();

        try {
            String i = databas.fetchSingle("SELECT max(ELEV_ID) FROM ELEV;");
            int elevID = Integer.parseInt(i) + 1;

            databas.insert("INSERT INTO ELEV (elev_id,fornamn, efternamn, sovsal) VALUES(" + elevID + ",'" + fornamn + "','" + efternamn + "'," + sovsal + ");");
            UppdateraTblElev();
            JOptionPane.showMessageDialog(null, " Elev har registerat ");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistreraElevActionPerformed

    private void btnTaBortElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortElevActionPerformed

        String elevID = lblElevId.getText();

        try {
            databas.update("update elevhem set prefekt= NUlL where prefekt =" + elevID + ";");
            databas.delete("delete from ELEV where elev_id=" + elevID + ";");
            UppdateraTblElev();
            JOptionPane.showMessageDialog(null, " Elev har avregistrerats ");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnTaBortElevActionPerformed

    private void btnRegistreraLärareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraLärareActionPerformed

        String fornamn = txtfldLärarNamn.getText();
        String efternamn = txtfldLärarEfternamn.getText();
        String Lösenord = txtfldLösenord.getText();

        try {
            if (chkbx.isSelected()) {

                String admin = "T";
                String i = databas.fetchSingle("SELECT max(LARAR_ID) FROM LARARE;");
                int lärarID = Integer.parseInt(i) + 1;

                databas.insert("INSERT INTO LARARE VALUES(" + lärarID + ",'" + fornamn + "','" + efternamn + "','" + Lösenord + "','" + admin + "');");
                this.setVisible(false); //this will close frame i.e. NewJFrame
                new Admin().setVisible(true);
                JOptionPane.showMessageDialog(null, " Lärare har registerat ");

            } else {

                String admin = "F";

                String i = databas.fetchSingle("SELECT max(LARAR_ID) FROM LARARE;");
                int lärarID = Integer.parseInt(i) + 1;

                databas.insert("INSERT INTO LARARE VALUES(" + lärarID + ",'" + fornamn + "','" + efternamn + "','" + Lösenord + "','" + admin + "');");
                this.setVisible(false); //this will close frame i.e. NewJFrame
                new Admin().setVisible(true);
                JOptionPane.showMessageDialog(null, " Lärare har registerat ");
            }
        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistreraLärareActionPerformed

    private void tblElevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblElevMouseClicked
        try {
            int rad = tblElev.getSelectedRow();
            String tabellClickad = (tblElev.getModel().getValueAt(rad, 0).toString());
            lblElevId.setText(tabellClickad);

            String elevNamn = databas.fetchSingle("select fornamn from elev where elev_id=" + tabellClickad + ";");
            txtfldElevNamn.setText(elevNamn);

            String elevEfternamn = databas.fetchSingle("select efternamn from elev where elev_id=" + tabellClickad + ";");
            txtfldElevEfternamn.setText(elevEfternamn);

            String elevSovsal = databas.fetchSingle("select sovsal from elev where elev_id=" + tabellClickad + ";");
            txtfldSovsal.setText(elevSovsal);

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_tblElevMouseClicked

    private void btnÄndraElevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraElevActionPerformed
        String elevId = lblElevId.getText();
        String elevNamn = txtfldElevNamn.getText();
        String elevEfternamn = txtfldElevEfternamn.getText();
        String elevSovsal = txtfldSovsal.getText();

        try {

            if (elevId.isEmpty()) {
                JOptionPane.showMessageDialog(null, " Välj en elev i tabellen ");

            } else {
                databas.update("Update ELEV set fornamn='" + elevNamn + "', efternamn='" + elevEfternamn + "', sovsal='" + elevSovsal + "' where elev_id=" + elevId + ";");
                UppdateraTblElev();
                JOptionPane.showMessageDialog(null, " Information om elev " + elevNamn + " " + elevEfternamn + " har ändrats ");

            }

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnÄndraElevActionPerformed

    private void btnTaBortLärareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortLärareActionPerformed

        String lärarId = lblLärarId.getText();

        try {
            if (lärarId.isEmpty()) {
                JOptionPane.showMessageDialog(null, " Välj en lärare i tabellen ");
            } else {
                databas.update("update kurs set kurslarare=null where kurslarare=" + lärarId + "");
                databas.update("update elevhem set forestandare=null where forestandare=" + lärarId + "");
                databas.delete("delete from LARARE where LARAR_ID=" + lärarId + ";");
                UppdateraTblLarare();
                JOptionPane.showMessageDialog(null, " Lärare har tagits bort ");
            }

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnTaBortLärareActionPerformed

    private void tblLarareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLarareMouseClicked
        try {
            int rad = tblLarare.getSelectedRow();
            String tabellClickad = (tblLarare.getModel().getValueAt(rad, 0).toString());
            lblLärarId.setText(tabellClickad);

            String lärarNamn = databas.fetchSingle("select fornamn from larare where larar_id=" + tabellClickad + ";");
            txtfldLärarNamn.setText(lärarNamn);

            String LärarEfternamn = databas.fetchSingle("select efternamn from larare where larar_id=" + tabellClickad + ";");
            txtfldLärarEfternamn.setText(LärarEfternamn);

            String lösenord = databas.fetchSingle("select losenord from larare where larar_id=" + tabellClickad + ";");
            txtfldLösenord.setText(lösenord);

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_tblLarareMouseClicked

    private void btnÄndraLärareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraLärareActionPerformed

        String fornamn = txtfldLärarNamn.getText();
        String efternamn = txtfldLärarEfternamn.getText();
        String Lösenord = txtfldLösenord.getText();
        String lararId = lblLärarId.getText();

        try {

            if (lararId.isEmpty()) {
                JOptionPane.showMessageDialog(null, " Välj en lärare i tabellen ");

            } else {
                if (chkbx.isSelected()) {

                    String admin = "T";
                    databas.update("Update larare set fornamn='" + fornamn + "', efternamn='" + efternamn + "', losenord='" + Lösenord + "', administrator='" + admin + "' where larar_id=" + lararId + ";");
                    UppdateraTblLarare();
                    JOptionPane.showMessageDialog(null, " Information om " + fornamn + " " + efternamn + " har ändrats ");
                } else {
                    String admin = "F";
                    databas.update("Update larare set fornamn='" + fornamn + "', efternamn='" + efternamn + "', losenord='" + Lösenord + "', administrator='" + admin + "' where larar_id=" + lararId + ";");
                    UppdateraTblLarare();
                    JOptionPane.showMessageDialog(null, " Information om " + fornamn + " " + efternamn + " har ändrats ");
                }
            }

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnÄndraLärareActionPerformed

    private void jcbElevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbElevhemActionPerformed
        String elevhem = (String) jcbElevhem.getSelectedItem();
        String poäng;

        try {
            poäng = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "'");
            lblPoäng.setText(poäng);
        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbElevhemActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String points;
        String elevhem = (String) jcbElevhem.getSelectedItem();

        try {
            String sAddPoäng = fldAdd.getText();
            int addPoäng = Integer.parseInt(sAddPoäng);

            try {

                String poäng = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "';");
                int nyaSummanPoäng = Integer.parseInt(poäng) + addPoäng;
                databas.update("UPDATE elevhem SET huspoang =" + nyaSummanPoäng + " where elevhemsnamn ='" + elevhem + "';");
                points = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "'");
                lblPoäng.setText(points);
                JOptionPane.showMessageDialog(null, " " + sAddPoäng + " poäng adderade till elevhem " + elevhem + " ");

            } catch (InfException ex) {
                System.out.println(ex.getMessage());
            }
        } catch (NumberFormatException z) {
            JOptionPane.showMessageDialog(null, "Ange en siffra, försök igen");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String elevhem = (String) jcbElevhem.getSelectedItem();
        String points;

        try {
            String sRemovePoäng = fldRemove.getText();
            int removePoäng = Integer.parseInt(sRemovePoäng);

            try {

                String poäng = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "';");
                int nyaSummanPoäng = Integer.parseInt(poäng) - removePoäng;
                databas.update("UPDATE elevhem SET huspoang =" + nyaSummanPoäng + " where elevhemsnamn ='" + elevhem + "';");
                points = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "'");
                lblPoäng.setText(points);
                JOptionPane.showMessageDialog(null, " " + sRemovePoäng + " poäng drogs av från elevhem " + elevhem + " ");

            } catch (InfException ex) {
                System.out.println(ex.getMessage());
            }
        } catch (NumberFormatException z) {
            JOptionPane.showMessageDialog(null, "Ange en siffra, försök igen");
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRegistreraKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraKursActionPerformed
        String kursLärare = (String) cbxKursLärare.getSelectedItem();
        String amne = (String) cbxÄmne.getSelectedItem();
        String kursNamn = fldKursNamn.getText();

        kursStartDatum.setDateFormatString("yyyy-MM-dd");
        DateFormat startDatum = new SimpleDateFormat("yyyy-MM-dd");
        kursSlutDatum.setDateFormatString("yyyy-MM-dd");
        DateFormat slutDatum = new SimpleDateFormat("yyyy-MM-dd");

        //Nedan tar bara fram siffror ur strängen från combo boxen
        String lärareString = kursLärare;
        String lärarID = lärareString.replaceAll("[^0-9]", "");

        String amneString = amne;
        String amnesID = amneString.replaceAll("[^0-9]", "");

        try {
            //Gör så att kursen som registreras får ett unikt kurs ID
            String i = databas.fetchSingle("SELECT max(KURS_ID) FROM KURS;");
            int kursID = Integer.parseInt(i) + 1;

            //Lägger till kursen i databasen, efter värdena användaren angav
            databas.insert("INSERT INTO KURS VALUES(" + kursID + ",'" + kursNamn + "','" + startDatum.format(kursStartDatum.getDate()) + "','" + slutDatum.format(kursSlutDatum.getDate()) + "'," + lärarID + "," + amnesID + ");");
            UppdateraTblKurser();
            JOptionPane.showMessageDialog(null, " Kursen har registerat ");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistreraKursActionPerformed

    private void btnTaBortKurserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortKurserActionPerformed
        String kursId = lblKursID.getText();

        try {
            if (kursId.isEmpty()) {
                JOptionPane.showMessageDialog(null, " Välj en kurs i tabellen ");
            } else {
//                databas.update("update kurs set kurslarare=null where kurslarare=" + lärarId + "");
                databas.delete("delete from HAR_BETYG_I where kurs_id=" + kursId + "");
                databas.delete("delete from REGISTRERAD_PA where kurs_id= " + kursId + "");
                databas.delete("delete from Kurs where kurs_ID=" + kursId + ";");

                UppdateraTblKurser();
                JOptionPane.showMessageDialog(null, " Kursen har tagits bort ");
            }

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnTaBortKurserActionPerformed

    private void tblKurserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKurserMouseClicked
        try {
            int rad = tblKurser.getSelectedRow();
            String tabellClickad = (tblKurser.getModel().getValueAt(rad, 0).toString());
            lblKursID.setText(tabellClickad);

            String kursNamn = databas.fetchSingle("select kursnamn from kurs where kurs_id=" + tabellClickad + ";");
            fldKursNamn.setText(kursNamn);

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblKurserMouseClicked

    private void btnÄndraKurserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraKurserActionPerformed
        String kursId = lblKursID.getText();
        String kursLärare = (String) cbxKursLärare.getSelectedItem();
        String amne = (String) cbxÄmne.getSelectedItem();
        String kursNamn = fldKursNamn.getText();

        kursStartDatum.setDateFormatString("yyyy-MM-dd");
        DateFormat startDatum = new SimpleDateFormat("yyyy-MM-dd");
        kursSlutDatum.setDateFormatString("yyyy-MM-dd");
        DateFormat slutDatum = new SimpleDateFormat("yyyy-MM-dd");

        //Nedan tar bara fram siffror ur strängen från combo boxen
        String lärareString = kursLärare;
        String lärarID = lärareString.replaceAll("[^0-9]", "");

        String amneString = amne;
        String amnesID = amneString.replaceAll("[^0-9]", "");
        try {

            if (kursId.isEmpty()) {
                JOptionPane.showMessageDialog(null, " Välj en kurs i tabellen ");

            } else {
                databas.update("Update KURS set kursnamn='" + kursNamn + "', kursstart='" + startDatum.format(kursStartDatum.getDate()) + "', kursslut='" + slutDatum.format(kursSlutDatum.getDate()) + "' , kurslarare=" + lärarID + ", amnestillhorighet=" + amnesID + " where kurs_id=" + kursId + ";");
                UppdateraTblKurser();
                JOptionPane.showMessageDialog(null, " Information om kursen " + kursNamn + " har ändrats ");

            }

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnÄndraKurserActionPerformed

    private void btnLoggaUtAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtAdminActionPerformed
        this.dispose();
        Start.main(null);
    }//GEN-LAST:event_btnLoggaUtAdminActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLoggaUtAdmin;
    private javax.swing.JButton btnRegistreraElev;
    private javax.swing.JButton btnRegistreraKurs;
    private javax.swing.JButton btnRegistreraLärare;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnTaBortElev;
    private javax.swing.JButton btnTaBortKurser;
    private javax.swing.JButton btnTaBortLärare;
    private javax.swing.JButton btnÄndraElev;
    private javax.swing.JButton btnÄndraKurser;
    private javax.swing.JButton btnÄndraLärare;
    private javax.swing.JComboBox<String> cbxKursLärare;
    private javax.swing.JComboBox<String> cbxÄmne;
    private javax.swing.JCheckBox chkbx;
    private javax.swing.JTextField fldAdd;
    private javax.swing.JTextField fldKursNamn;
    private javax.swing.JTextField fldRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbElevhem;
    private com.toedter.calendar.JDateChooser kursSlutDatum;
    private com.toedter.calendar.JDateChooser kursStartDatum;
    private javax.swing.JLabel lblElevId;
    private javax.swing.JLabel lblKursID;
    private javax.swing.JLabel lblLärarId;
    private javax.swing.JLabel lblPoäng;
    private javax.swing.JTable tblElev;
    private javax.swing.JTable tblKurser;
    private javax.swing.JTable tblLarare;
    private javax.swing.JTextField txtfldElevEfternamn;
    private javax.swing.JTextField txtfldElevNamn;
    private javax.swing.JTextField txtfldLärarEfternamn;
    private javax.swing.JTextField txtfldLärarNamn;
    private javax.swing.JTextField txtfldLösenord;
    private javax.swing.JTextField txtfldSovsal;
    // End of variables declaration//GEN-END:variables
    private void connectDB() {
        try {
            databas = new InfDB("C:\\Hogwarts Projekt\\HOGDB (1).FDB");
            System.out.println("Lyckads");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void fyllTblElev() {
        DMElev.addColumn("ID");
        DMElev.addColumn("Förnamn");
        DMElev.addColumn("Efternamn");
        DMElev.addColumn("Sovsal");

        try {
            ArrayList<HashMap<String, String>> elevGrejor;
            elevGrejor = databas.fetchRows("Select elev_id, fornamn, efternamn, sovsal from elev;");

            for (HashMap<String, String> grejor : elevGrejor) {
                String[] rad = {grejor.get("ELEV_ID"), grejor.get("FORNAMN"), grejor.get("EFTERNAMN"), grejor.get("SOVSAL")};
                DMElev.addRow(rad);
            }
            tblElev.setModel(DMElev);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

    public void fyllTblLarare() {
        DMLarare.addColumn("ID");
        DMLarare.addColumn("Förnamn");
        DMLarare.addColumn("Efternamn");
        DMLarare.addColumn("Lösenord");
        DMLarare.addColumn("Admin");

        try {
            ArrayList<HashMap<String, String>> LararGrejor;
            LararGrejor = databas.fetchRows("Select larar_id, fornamn, efternamn, losenord, administrator from larare;");

            for (HashMap<String, String> grejor : LararGrejor) {
                String[] rad = {grejor.get("LARAR_ID"), grejor.get("FORNAMN"), grejor.get("EFTERNAMN"), grejor.get("LOSENORD"), grejor.get("ADMINISTRATOR")};
                DMLarare.addRow(rad);
            }
            tblLarare.setModel(DMLarare);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

    public void fyllTblKurser() {
        DMKurser.addColumn("ID");
        DMKurser.addColumn("Kursnamn");
        DMKurser.addColumn("Start");
        DMKurser.addColumn("Slut");
        DMKurser.addColumn("Lärare");
        DMKurser.addColumn("Ämne");

        try {
            ArrayList<HashMap<String, String>> kursGrejor;
            kursGrejor = databas.fetchRows("Select kurs_id, kursnamn, kursstart, kursslut, kursLarare, amnestillhorighet from kurs;");

            for (HashMap<String, String> grejor : kursGrejor) {
                String[] rad = {grejor.get("KURS_ID"), grejor.get("KURSNAMN"), grejor.get("KURSSTART"), grejor.get("KURSSLUT"), grejor.get("KURSLARARE"), grejor.get("AMNESTILLHORIGHET")};
                DMKurser.addRow(rad);
            }
            tblKurser.setModel(DMKurser);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

    public void UppdateraTblKurser() {
        // Tömmer befintlig datamodell
        if (DMKurser.getRowCount() > 0) {
            for (int i = DMKurser.getRowCount() - 1; i > -1; i--) {
                DMKurser.removeRow(i);
            }
            //Fyller datamodellen igen men inkluderande ändringar som har skett
            try {
                ArrayList<HashMap<String, String>> kursGrejor;
                kursGrejor = databas.fetchRows("Select kurs_id, kursnamn, kursstart, kursslut, kursLarare, amnestillhorighet from kurs;");

                for (HashMap<String, String> grejor : kursGrejor) {
                    String[] rad = {grejor.get("KURS_ID"), grejor.get("KURSNAMN"), grejor.get("KURSSTART"), grejor.get("KURSSLUT"), grejor.get("KURSLARARE"), grejor.get("AMNESTILLHORIGHET")};
                    DMKurser.addRow(rad);
                }
                tblKurser.setModel(DMKurser);

            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "");

            }

        }
    }

    public void UppdateraTblLarare() {

        if (DMLarare.getRowCount() > 0) {
            for (int i = DMLarare.getRowCount() - 1; i > -1; i--) {
                DMLarare.removeRow(i);
            }
        }
        try {
            ArrayList<HashMap<String, String>> LararGrejor;
            LararGrejor = databas.fetchRows("Select larar_id, fornamn, efternamn, losenord, administrator from larare;");

            for (HashMap<String, String> grejor : LararGrejor) {
                String[] rad = {grejor.get("LARAR_ID"), grejor.get("FORNAMN"), grejor.get("EFTERNAMN"), grejor.get("LOSENORD"), grejor.get("ADMINISTRATOR")};
                DMLarare.addRow(rad);
            }
            tblLarare.setModel(DMLarare);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

    public void UppdateraTblElev() {
        try {
            ArrayList<HashMap<String, String>> elevGrejor;
            elevGrejor = databas.fetchRows("Select elev_id, fornamn, efternamn, sovsal from elev;");

            if (DMElev.getRowCount() > 0) {
                for (int i = DMElev.getRowCount() - 1; i > -1; i--) {
                    DMElev.removeRow(i);
                }
            }

            for (HashMap<String, String> grejor : elevGrejor) {
                String[] rad = {grejor.get("ELEV_ID"), grejor.get("FORNAMN"), grejor.get("EFTERNAMN"), grejor.get("SOVSAL")};
                DMElev.addRow(rad);
            }
            tblElev.setModel(DMElev);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

    public void fyllKursLärareComboBox() {
        try {
            ArrayList<HashMap<String, String>> kursLärare = databas.fetchRows("Select larar_id, fornamn, efternamn from larare");

            for (HashMap<String, String> läraren : kursLärare) {
                String lararID = läraren.get("LARAR_ID");
                String lararFörnamn = läraren.get("FORNAMN");
                String lararEfternamn = läraren.get("EFTERNAMN");

                cbxKursLärare.addItem("(" + lararID + ")" + " " + lararFörnamn + " " + lararEfternamn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");
        }
    }

    public void fyllÄmneComboBox() {
        try {
            ArrayList<HashMap<String, String>> ämnen = databas.fetchRows("Select AMNE_ID, AMNESNAMN from AMNE");

            for (HashMap<String, String> ämne : ämnen) {
                String amneID = ämne.get("AMNE_ID");
                String amnesNamn = ämne.get("AMNESNAMN");

                cbxÄmne.addItem("(" + amneID + ")" + " " + amnesNamn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");
        }
    }
}
