package javaapplication1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class TeacherWindow extends javax.swing.JFrame {

    private InfDB databas;
    DefaultTableModel DMElev = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    public TeacherWindow() {

        initComponents();
        connectDB();
        fyllElevComboBox();
        fyllTblElev();
        fyllKursComboBox();
        fyllElevComboBox2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        btnLoggaUtLärare = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pfldGammalt = new javax.swing.JPasswordField();
        pfldNytt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnÄndraLösenord = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfldElevNamn = new javax.swing.JTextField();
        txtfldElevEfternamn = new javax.swing.JTextField();
        txtfldSovsal = new javax.swing.JTextField();
        btnRegistrera = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblElevId = new javax.swing.JLabel();
        btnÄndra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblElev = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbElevhem = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        fldAdd = new javax.swing.JTextField();
        fldRemove = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblPoäng = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cbxElev = new javax.swing.JComboBox<>();
        bntLäggTillKursBetyg = new javax.swing.JButton();
        btnÄndraKursBetyg = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbxKurs = new javax.swing.JComboBox<>();
        cbxBetyg = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbxBetyg1 = new javax.swing.JComboBox<>();
        cbxKurs1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbxElev1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lärare");

        jTabbedPane1.setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Välkommen:");

        lblFornamn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFornamn.setText("Förnamn");

        lblEfternamn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEfternamn.setText("Efternamn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFornamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEfternamn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFornamn)
                    .addComponent(lblEfternamn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLoggaUtLärare.setText("Logga ut");
        btnLoggaUtLärare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtLärareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoggaUtLärare)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnLoggaUtLärare)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Home", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Gammalt Lösenord:");

        jLabel3.setText("Nytt Lösenord:");

        btnÄndraLösenord.setText("Ändra Lösenord");
        btnÄndraLösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraLösenordActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ändra Lösenord");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfldNytt)
                    .addComponent(pfldGammalt)
                    .addComponent(btnÄndraLösenord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pfldGammalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pfldNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnÄndraLösenord)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lösenord", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Förnamn: ");

        jLabel7.setText("Efternamn:");

        jLabel8.setText("Sovsal:");

        btnRegistrera.setText("Registerara");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Registrera/Ändra Elev");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("Elev ID:");

        btnÄndra.setText("Ändra");
        btnÄndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraActionPerformed(evt);
            }
        });

        tblElev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblElev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblElevMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblElev);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfldElevEfternamn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfldElevNamn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElevId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfldSovsal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnÄndra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(lblElevId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfldElevNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfldElevEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfldSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrera)
                            .addComponent(btnÄndra))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Elever", jPanel4);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Lägga till huspoäng");

        jLabel10.setText("Dra av huspoäng");

        jcbElevhem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gryfindor", "Slytherin", "Hufflepuff", "Ravenclaw" }));
        jcbElevhem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbElevhemActionPerformed(evt);
            }
        });

        jLabel11.setText("Huspoäng:");

        fldRemove.setToolTipText("");

        btnAdd.setText("Lägg till");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Dra av");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel12.setText("Välj elevhem");

        lblPoäng.setText("               ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fldRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel12)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jcbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPoäng)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblPoäng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Huspoäng", jPanel9);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Lägg till kursbetyg");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(133, 133, 133))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bntLäggTillKursBetyg.setText("Lägg till");
        bntLäggTillKursBetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLäggTillKursBetygActionPerformed(evt);
            }
        });

        btnÄndraKursBetyg.setText("Ändra");
        btnÄndraKursBetyg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraKursBetygActionPerformed(evt);
            }
        });

        jLabel14.setText("Kurs:");

        jLabel15.setText("Betyg:");

        jLabel17.setText("Elev:");

        cbxBetyg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T (Troll)", "D (Dreadful)", "P (Poor)", "A (Acceptable)", "E (Exceeds Expectations)", "O (OutStanding)" }));

        jLabel18.setText("Betyg:");

        cbxBetyg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T (Troll)", "D (Dreadful)", "P (Poor)", "A (Acceptable)", "E (Exceeds Expectations)", "O (OutStanding)" }));

        jLabel19.setText("Kurs:");

        cbxElev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElev1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Elev:");

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setText("Ändra befintligt betyg ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(133, 133, 133))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxElev, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(3, 3, 3)
                                .addComponent(cbxBetyg, 0, 1, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(3, 3, 3)
                            .addComponent(cbxBetyg1, 0, 1, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbxElev1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbxKurs1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(bntLäggTillKursBetyg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnÄndraKursBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbxKurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbxBetyg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxElev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cbxKurs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cbxBetyg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntLäggTillKursBetyg)
                    .addComponent(btnÄndraKursBetyg))
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Kurser", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnÄndraLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraLösenordActionPerformed
        String fornamn = (String) lblFornamn.getText();
        String efternamn = (String) lblEfternamn.getText();
        char[] gammaltLösen = pfldGammalt.getPassword();
        char[] nyttLösen = pfldNytt.getPassword();
        String OldPass = new String(gammaltLösen);
        String NewPass = new String(nyttLösen);

        try {
            String nuvarandeLösen = databas.fetchSingle("select losenord from larare where fornamn='" + fornamn + "' and efternamn='" + efternamn + "';");

            if (OldPass.contains(nuvarandeLösen)) {
                databas.update("update larare set losenord='" + NewPass + "'where fornamn='" + fornamn + "' and efternamn='" + efternamn + "';");
                JOptionPane.showMessageDialog(null, "Succes!");
            } else {
                JOptionPane.showMessageDialog(null, "Stämmer ej med nuvarade lösenord!");
            }

        } catch (InfException ex) {
            Logger.getLogger(TeacherWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnÄndraLösenordActionPerformed

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        String fornamn = txtfldElevNamn.getText();
        String efternamn = txtfldElevEfternamn.getText();
        String sovsal = txtfldSovsal.getText();

        try {
            String i = databas.fetchSingle("SELECT max(ELEV_ID) FROM ELEV;");
            int elevID = Integer.parseInt(i) + 1;

            databas.insert("INSERT INTO ELEV (elev_id,fornamn, efternamn, sovsal) VALUES(" + elevID + ",'" + fornamn + "','" + efternamn + "'," + sovsal + ");");
            UppdateraTblElev();
            JOptionPane.showMessageDialog(null, " Elev har registerat ");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        String elevhem = (String) jcbElevhem.getSelectedItem();
        String points;

        try {
            String sRemovePoäng = fldRemove.getText();
            int removePoäng = Integer.parseInt(sRemovePoäng);

            try {

                String poäng = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "';");
                int nyaSummanPoäng = Integer.parseInt(poäng) - removePoäng;
                databas.update("UPDATE elevhem SET huspoang =" + nyaSummanPoäng + " where elevhemsnamn ='" + elevhem + "';");
                points = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "'");
                lblPoäng.setText(points);
                JOptionPane.showMessageDialog(null, " " + sRemovePoäng + " poäng drogs av från elevhem " + elevhem + " ");

            } catch (InfException ex) {
                System.out.println(ex.getMessage());
            }
        } catch (NumberFormatException z) {
            JOptionPane.showMessageDialog(null, "Ange en siffra, försök igen");
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String points;
        String elevhem = (String) jcbElevhem.getSelectedItem();

        try {
            String sAddPoäng = fldAdd.getText();
            int addPoäng = Integer.parseInt(sAddPoäng);

            try {

                String poäng = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "';");
                int nyaSummanPoäng = Integer.parseInt(poäng) + addPoäng;
                databas.update("UPDATE elevhem SET huspoang =" + nyaSummanPoäng + " where elevhemsnamn ='" + elevhem + "';");
                points = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "'");
                lblPoäng.setText(points);
                JOptionPane.showMessageDialog(null, " " + sAddPoäng + " poäng adderade till elevhem " + elevhem + " ");

            } catch (InfException ex) {
                System.out.println(ex.getMessage());
            }
        } catch (NumberFormatException z) {
            JOptionPane.showMessageDialog(null, "Ange en siffra, försök igen");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jcbElevhemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbElevhemActionPerformed
        String elevhem = (String) jcbElevhem.getSelectedItem();
        String poäng;

        try {
            poäng = databas.fetchSingle("Select huspoang from elevhem where elevhemsnamn='" + elevhem + "'");
            lblPoäng.setText(poäng);
        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcbElevhemActionPerformed

    private void btnÄndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraActionPerformed
        String elevId = lblElevId.getText();
        String elevNamn = txtfldElevNamn.getText();
        String elevEfternamn = txtfldElevEfternamn.getText();
        String elevSovsal = txtfldSovsal.getText();

        try {

            if (elevId.isEmpty()) {
                JOptionPane.showMessageDialog(null, " Välj en elev i tabellen ");

            } else {
                databas.update("Update ELEV set fornamn='" + elevNamn + "', efternamn='" + elevEfternamn + "', sovsal='" + elevSovsal + "' where elev_id=" + elevId + ";");
                UppdateraTblElev();
                JOptionPane.showMessageDialog(null, " Information om elev har ändrats ");

            }

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnÄndraActionPerformed

    private void bntLäggTillKursBetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLäggTillKursBetygActionPerformed
        //Skapar lokala variablar från det som väljs från comboboxerna
        String elev = (String) cbxElev.getSelectedItem();
        String kurs = (String) cbxKurs.getSelectedItem();
        String betyg = (String) cbxBetyg.getSelectedItem();

        try {
            //Nedan tar bara fram siffror ur strängen från combo boxen, för att använda id siffrorna i sql frågan.
            String elevString = elev;
            String elevID = elevString.replaceAll("[^0-9]", "");

            String kursString = kurs;
            String kursID = kursString.replaceAll("[^0-9]", "");

            //Delar upp strängen från betyg comboboxen, pga att får bara va en bokstav
            String string = betyg;
            String[] delar = string.split(" ");
            String betyget = delar[0];

            //Lägger till det nya betyget för kursen i databsen. 
            databas.insert("INSERT INTO HAR_BETYG_I VALUES(" + elevID + "," + kursID + ",'" + betyget + "');");
            JOptionPane.showMessageDialog(null, " Betyget för kursen har registerats för eleven ");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_bntLäggTillKursBetygActionPerformed

    private void tblElevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblElevMouseClicked
        try {
            int rad = tblElev.getSelectedRow();
            String tabellClickad = (tblElev.getModel().getValueAt(rad, 0).toString());
            lblElevId.setText(tabellClickad);

            String elevNamn = databas.fetchSingle("select fornamn from elev where elev_id=" + tabellClickad + ";");
            txtfldElevNamn.setText(elevNamn);

            String elevEfternamn = databas.fetchSingle("select efternamn from elev where elev_id=" + tabellClickad + ";");
            txtfldElevEfternamn.setText(elevEfternamn);

            String elevSovsal = databas.fetchSingle("select sovsal from elev where elev_id=" + tabellClickad + ";");
            txtfldSovsal.setText(elevSovsal);

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblElevMouseClicked

    private void btnÄndraKursBetygActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraKursBetygActionPerformed
        String elev1 = (String) cbxElev1.getSelectedItem();
        String kurs1 = (String) cbxKurs1.getSelectedItem();
        String betyg1 = (String) cbxBetyg1.getSelectedItem();

        try {

            //Nedan tar bara fram siffror ur strängen från combo boxen, för att använda id siffrorna i sql frågan.
            String elevString = elev1;
            String elevID = elevString.replaceAll("[^0-9]", "");

            String kursString = kurs1;
            String kursID = kursString.replaceAll("[^0-9]", "");

            //Delar upp strängen från betyg comboboxen, pga att får bara va en bokstav
            String string = betyg1;
            String[] delar = string.split(" ");
            String betyget = delar[0];

            //Uppdaterar betyget för en befintlig kurs  
            databas.update("Update har_betyg_i set KURSBETYG='" + betyget + "' where KURS_ID=" + kursID + " and ELEV_ID=" + elevID + ";");
            JOptionPane.showMessageDialog(null, " Betyget för kursen har ändrats ");

        } catch (InfException ex) {
            Logger.getLogger(ElevhemWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnÄndraKursBetygActionPerformed

    private void cbxElev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElev1ActionPerformed

        String elev = (String) cbxElev1.getSelectedItem();

        try {
            if (cbxKurs1.getItemCount() > 0) {

                cbxKurs1.removeAllItems();

            }

            //Nedan tar bara fram siffror ur strängen från combo boxen, för att använda id siffrorna i sql frågan.
            String elevString = elev;
            String elevID = elevString.replaceAll("[^0-9]", "");

            ArrayList<HashMap<String, String>> kurser = databas.fetchRows("select har_betyg_i.kurs_id, kursnamn from har_betyg_i join kurs on kurs.kurs_id=har_betyg_i.KURS_ID where elev_id=" + elevID + ";");

            for (HashMap<String, String> kurs : kurser) {
                String kursNamn = kurs.get("KURSNAMN");
                String kursId = kurs.get("KURS_ID");

                cbxKurs1.addItem("(" + kursId + ") " + kursNamn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");
        } catch (NullPointerException x) {

        }
    }//GEN-LAST:event_cbxElev1ActionPerformed

    private void btnLoggaUtLärareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtLärareActionPerformed
        this.dispose();
        Start.main(null);
    }//GEN-LAST:event_btnLoggaUtLärareActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TeacherWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLäggTillKursBetyg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLoggaUtLärare;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnÄndra;
    private javax.swing.JButton btnÄndraKursBetyg;
    private javax.swing.JButton btnÄndraLösenord;
    private javax.swing.JComboBox<String> cbxBetyg;
    private javax.swing.JComboBox<String> cbxBetyg1;
    private javax.swing.JComboBox<String> cbxElev;
    private javax.swing.JComboBox<String> cbxElev1;
    private javax.swing.JComboBox<String> cbxKurs;
    private javax.swing.JComboBox<String> cbxKurs1;
    private javax.swing.JTextField fldAdd;
    private javax.swing.JTextField fldRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbElevhem;
    public static javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblElevId;
    public static javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblPoäng;
    private javax.swing.JPasswordField pfldGammalt;
    private javax.swing.JPasswordField pfldNytt;
    private javax.swing.JTable tblElev;
    private javax.swing.JTextField txtfldElevEfternamn;
    private javax.swing.JTextField txtfldElevNamn;
    private javax.swing.JTextField txtfldSovsal;
    // End of variables declaration//GEN-END:variables
private void connectDB() {
        try {
            databas = new InfDB("C:\\Hogwarts Projekt\\HOGDB (1).FDB");
            System.out.println("Lyckads");

        } catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void fyllElevComboBox() {
        try {
            ArrayList<HashMap<String, String>> elev = databas.fetchRows("Select elev_id, fornamn, efternamn from elev ");

            for (HashMap<String, String> eleven : elev) {
                String elevID = eleven.get("ELEV_ID");
                String elevFörnamn = eleven.get("FORNAMN");
                String elevEfternamn = eleven.get("EFTERNAMN");

                cbxElev.addItem("(" + elevID + ")" + " " + elevFörnamn + " " + elevEfternamn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");
        }
    }

    public void fyllElevComboBox2() {
        try {
            ArrayList<HashMap<String, String>> elev = databas.fetchRows("Select elev_id, fornamn, efternamn from elev ");

            for (HashMap<String, String> eleven : elev) {
                String elevID = eleven.get("ELEV_ID");
                String elevFörnamn = eleven.get("FORNAMN");
                String elevEfternamn = eleven.get("EFTERNAMN");

                cbxElev1.addItem("(" + elevID + ")" + " " + elevFörnamn + " " + elevEfternamn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");
        }
    }

    public void fyllKursComboBox() {
        try {
            ArrayList<HashMap<String, String>> kurser = databas.fetchRows("select kurs_id, kursnamn from kurs ");

            for (HashMap<String, String> kurs : kurser) {
                String kursNamn = kurs.get("KURSNAMN");
                String kursId = kurs.get("KURS_ID");

                cbxKurs.addItem("(" + kursId + ") " + kursNamn);
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");
        }
    }

    public void fyllTblElev() {
        DMElev.addColumn("ID");
        DMElev.addColumn("Förnamn");
        DMElev.addColumn("Efternamn");
        DMElev.addColumn("Sovsal");

        try {
            ArrayList<HashMap<String, String>> elevGrejor;
            elevGrejor = databas.fetchRows("Select elev_id, fornamn, efternamn, sovsal from elev;");

            for (HashMap<String, String> grejor : elevGrejor) {
                String[] rad = {grejor.get("ELEV_ID"), grejor.get("FORNAMN"), grejor.get("EFTERNAMN"), grejor.get("SOVSAL")};
                DMElev.addRow(rad);
            }
            tblElev.setModel(DMElev);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

    public void UppdateraTblElev() {
        try {
            ArrayList<HashMap<String, String>> elevGrejor;
            elevGrejor = databas.fetchRows("Select elev_id, fornamn, efternamn, sovsal from elev;");

            if (DMElev.getRowCount() > 0) {
                for (int i = DMElev.getRowCount() - 1; i > -1; i--) {
                    DMElev.removeRow(i);
                }
            }

            for (HashMap<String, String> grejor : elevGrejor) {
                String[] rad = {grejor.get("ELEV_ID"), grejor.get("FORNAMN"), grejor.get("EFTERNAMN"), grejor.get("SOVSAL")};
                DMElev.addRow(rad);
            }
            tblElev.setModel(DMElev);

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "");

        }

    }

}
